language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE lcds_test;'
  - cp config/db.test.php config/db.example.php

install:
  - composer install
  - ./yii migrate --interactive=0

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/codecept run
