language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE lcds;'
  - cp config/db.travis.php config/db.php
  - cp config/params.exemple.php config/params.php

install:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install
  - ./yii migration

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini


