language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE lcds_test;'
  - cp config/db.test.php config/db.example.php
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install
  - ./yii migrate --interactive=0

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer exec codecept run
